name: Deploy Next.js to EC2 with Nginx

name: Deploy Next.js to EC2 with Nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: frontend
      run: npm ci

    - name: Cache Next.js build cache
      uses: actions/cache@v3
      with:
        path: frontend/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: ${{ runner.os }}-nextjs-

    - name: Create .env file
      working-directory: frontend
      run: echo "NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}" > .env

    - name: Build Next.js application
      working-directory: frontend
      run: npm run build

    - name: Archive build artefacts
      working-directory: frontend
      run: tar -czf ../nextjs-build.tar.gz .next package.json package-lock.json .env

    - name: Install SSH & rsync
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Upload artefacts to EC2 via rsync
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem

        ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP \
          "sudo mkdir -p /home/ubuntu/careear-frontend && sudo chown -R $EC2_USER:$EC2_USER /home/ubuntu/careear-frontend"

        rsync -avz --delete -e "ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no" \
          nextjs-build.tar.gz $EC2_USER@$EC2_IP:/home/ubuntu/careear-frontend/

    - name: Deploy on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem

        ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
          set -e
          cd /home/ubuntu/careear-frontend

          tar -xzf nextjs-build.tar.gz

          npm install --production --prefer-offline --no-audit

          if ! command -v pm2 >/dev/null 2>&1; then
            sudo npm install -g pm2
          fi

          pm2 stop careear-frontend || true
          pm2 delete careear-frontend || true
          pm2 start npm --name careear-frontend -- run start -- -p 3000

          pm2 save
          pm2 startup -u $(whoami) --hp /home/ubuntu

          sudo systemctl restart nginx
        EOF
