name: Deploy Next.js to EC2 with Nginx

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # one place to change the folder name if you ever move it
    env:
      PROJECT_DIR: frontend
      REMOTE_DIR: /home/ubuntu/careear-frontend   # <- keep your typo if the folder already exists
      NODE_VERSION: "18"

    steps:
    # 1️⃣  Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣  Node setup & cache
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ${{ env.PROJECT_DIR }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

    - name: Install dependencies
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm ci    # reproducible installs

    # 3️⃣  Build
    - name: Cache Next.js build cache
      uses: actions/cache@v3
      with:
        path: ${{ env.PROJECT_DIR }}/.next/cache
        key: ${{ runner.os }}-next-${{ hashFiles('frontend/package-lock.json') }}

    - name: Inject env vars
      working-directory: ${{ env.PROJECT_DIR }}
      run: echo "NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}" >> .env

    - name: Build Next.js app
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm run build

    # 4️⃣  Package build artefacts (keeps repo slim on the server)
    - name: Create build archive
      run: |
        tar -czf nextjs-build.tar.gz \
          -C ${{ env.PROJECT_DIR }} .next package.json .env

    # 5️⃣  Copy to EC2
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 13.60.201.226 >> ~/.ssh/known_hosts

    - name: Upload build archive to EC2
      env:
        SSH_KEY: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA8m6kWrYnnxFV3AP2CtT/spbSosEaG7pbj/KSbieQfr09ny0Y
IAszcLvKS8D8AuKvWMQu4TvfFy8BmOrYWMUX+uQqQHAJ45FsxOqGRvgGnKvNom0K
kBDfWDLYqrUli/dnqPFRkeGaYfxWXFbwW9f+QBDzKRABKwuHbvsyhCwNqGvN4luZ
gGxnkVtWrTdi5l5yJTalzvAbKLlhZoChCc8k0blpBYypEgpaQf4OfV7dCo2Wrnnq
K4RFZckqCfsBqirUseDxq84jdmNmucBM+wg22i1mYY7Z+9eDcR2wZQ2gJjIXEf8O
C6z5Er3EggA8TzFVRDAkx1sl70y1ALYxjqEU7QIDAQABAoIBABynWyGlmfVBFUbV
6QTKvBYdoXO/IxjX4+6Vmx0N7BQuxdPEfq9642+Voollm+Oza0owleHlM68HzUaH
q16CnRz4Ts4i7+hHzfVQSuKkehOWcs2Z2b/BXsSL7fPvSSrL6SKcsyls4tRmAMcV
N3+DffeQiUz3KUwvJqjFY+kfU9Xt/RmR8cuy6THggReoTpxE1Ir+yUcrYxpJtp/r
JcsUq3VQOgN5+nJUpV6sl8E2xLq8DrG0qSjktu0RtNM2iRbrn77uHmOC10AZBZMK
IEEMxQC26+GgdJDJVbvIq7ux3r+EYAo9vDSEs8okwCfa0nQjNjew6hACkDbgtaTr
pqbqUYECgYEA+k05rJcR3SycDTpGk1mJTy2vAoungAPDfFjUHdN3GtWwfW1R9q93
SWbN5yzgk69uHvLV18wYbuQVgDvcOucqZNZUR8GLJ9vEWTLbxkkpoGl5cEtB7q7b
IjT19S7dZoE8TIuJP/vpOYMrjaf7rrkVCjUCFNm0l2y+79udDwnujVECgYEA9/ON
jhJgqIIryfB7WDkapUDKDs6IDT3JYVS8yEceHmjX9qSXCgWJn6bW1xO7OzouBz2t
oKG46jYQZzakrqdZUU0+W/89iZ5yLsXDK3CYp0/8lX+3drpQ+Aj7Q0vyrDarpKFe
p9kjHlF8lxI8Q5cc8UR77z67on1/8C/2LstCNt0CgYEA17MHOalyVpSj4m5O9Zpa
TuaChAIPla0ooJb4LL/YS0LNdjloQdrSRGoYlNjCq+KpVnhUOkSC5cUelkR/tC8U
BJQDS1cJ8Y5c9bVzWbwg6EEcyt2/8s2ywBa9ws3hM/25FgnFfGM9iDd2p/uUU+zh
qcsmgQtfqoKnRJKQFa6sahECgYBvK7wkHwlHhFWtzS0AeVoBDfOKf/9wMGvCQAQE
qB5Q9CEgbNtrmuABvQRGmoowG/3XMUhP5TLLkEH6hP2BcXcShNeY1+/3bBs17WV8
bJeFLM/LF+BiU1dKXnyJx9uea0S6I8AU8b5VMaPy+DIc+/v2EQagVjg6uppKTrbK
dEfT4QKBgQDPvdcOfj2NW0sjM3DDVtW5iZF1wA1GAvmC//Cfff9HB+CHTwltURWV
lUctFdRfqDYMY6XI9LJal/VyegF3cHii7lpHDMgtt6qpuhyJ/9C/MgUKviHEoz/V
q7rrZmMd8LpudDaoiXcpGJJFgg+b6rqjmIvXe5pOTAv002WUw7K5Jw==
-----END RSA PRIVATE KEY-----   # consider renaming this secret to EC2_SSH_KEY
      run: |
        echo "$SSH_KEY" | tr -d '\r' > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem
        rsync -avz --delete -e "ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no" \
          nextjs-build.tar.gz \
          ${{ secrets.EC2_USER }}@13.60.201.226:${{ env.REMOTE_DIR }}/

    # 6️⃣  Deploy on the VM
    - name: Unpack & start app on EC2
      env:
        SSH_KEY: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA8m6kWrYnnxFV3AP2CtT/spbSosEaG7pbj/KSbieQfr09ny0Y
IAszcLvKS8D8AuKvWMQu4TvfFy8BmOrYWMUX+uQqQHAJ45FsxOqGRvgGnKvNom0K
kBDfWDLYqrUli/dnqPFRkeGaYfxWXFbwW9f+QBDzKRABKwuHbvsyhCwNqGvN4luZ
gGxnkVtWrTdi5l5yJTalzvAbKLlhZoChCc8k0blpBYypEgpaQf4OfV7dCo2Wrnnq
K4RFZckqCfsBqirUseDxq84jdmNmucBM+wg22i1mYY7Z+9eDcR2wZQ2gJjIXEf8O
C6z5Er3EggA8TzFVRDAkx1sl70y1ALYxjqEU7QIDAQABAoIBABynWyGlmfVBFUbV
6QTKvBYdoXO/IxjX4+6Vmx0N7BQuxdPEfq9642+Voollm+Oza0owleHlM68HzUaH
q16CnRz4Ts4i7+hHzfVQSuKkehOWcs2Z2b/BXsSL7fPvSSrL6SKcsyls4tRmAMcV
N3+DffeQiUz3KUwvJqjFY+kfU9Xt/RmR8cuy6THggReoTpxE1Ir+yUcrYxpJtp/r
JcsUq3VQOgN5+nJUpV6sl8E2xLq8DrG0qSjktu0RtNM2iRbrn77uHmOC10AZBZMK
IEEMxQC26+GgdJDJVbvIq7ux3r+EYAo9vDSEs8okwCfa0nQjNjew6hACkDbgtaTr
pqbqUYECgYEA+k05rJcR3SycDTpGk1mJTy2vAoungAPDfFjUHdN3GtWwfW1R9q93
SWbN5yzgk69uHvLV18wYbuQVgDvcOucqZNZUR8GLJ9vEWTLbxkkpoGl5cEtB7q7b
IjT19S7dZoE8TIuJP/vpOYMrjaf7rrkVCjUCFNm0l2y+79udDwnujVECgYEA9/ON
jhJgqIIryfB7WDkapUDKDs6IDT3JYVS8yEceHmjX9qSXCgWJn6bW1xO7OzouBz2t
oKG46jYQZzakrqdZUU0+W/89iZ5yLsXDK3CYp0/8lX+3drpQ+Aj7Q0vyrDarpKFe
p9kjHlF8lxI8Q5cc8UR77z67on1/8C/2LstCNt0CgYEA17MHOalyVpSj4m5O9Zpa
TuaChAIPla0ooJb4LL/YS0LNdjloQdrSRGoYlNjCq+KpVnhUOkSC5cUelkR/tC8U
BJQDS1cJ8Y5c9bVzWbwg6EEcyt2/8s2ywBa9ws3hM/25FgnFfGM9iDd2p/uUU+zh
qcsmgQtfqoKnRJKQFa6sahECgYBvK7wkHwlHhFWtzS0AeVoBDfOKf/9wMGvCQAQE
qB5Q9CEgbNtrmuABvQRGmoowG/3XMUhP5TLLkEH6hP2BcXcShNeY1+/3bBs17WV8
bJeFLM/LF+BiU1dKXnyJx9uea0S6I8AU8b5VMaPy+DIc+/v2EQagVjg6uppKTrbK
dEfT4QKBgQDPvdcOfj2NW0sjM3DDVtW5iZF1wA1GAvmC//Cfff9HB+CHTwltURWV
lUctFdRfqDYMY6XI9LJal/VyegF3cHii7lpHDMgtt6qpuhyJ/9C/MgUKviHEoz/V
q7rrZmMd8LpudDaoiXcpGJJFgg+b6rqjmIvXe5pOTAv002WUw7K5Jw==
-----END RSA PRIVATE KEY-----
        NEXT_PUBLIC_BACKEND_URL: ${{ vars.NEXT_PUBLIC_BACKEND_URL }}
      run: |
        echo "$SSH_KEY" | tr -d '\r' > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem

        ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no ${{
          secrets.EC2_USER }}@13.60.201.226 << 'EOF'
          set -e

          REMOTE_DIR=${REMOTE_DIR}
          cd $REMOTE_DIR

          # unpack new build
          tar -xzf nextjs-build.tar.gz
          rm nextjs-build.tar.gz

          # install only production deps
          npm ci --production

          # PM2 (keeps app alive)
          if ! command -v pm2 >/dev/null 2>&1; then
            sudo npm i -g pm2
          fi

          pm2 delete careear-frontend || true
          pm2 start npm --name careear-frontend -- start -- -p 3000
          pm2 save

          # reload nginx
          sudo systemctl restart nginx
        EOF
